CREATE TABLE IF NOT EXISTS TEST_PROGRESS (
    GROUP_KEY VARCHAR(100) NOT NULL,
    PARTITION_ID BIGINT NOT NULL,
    EVENT_ID VARCHAR(100) NOT NULL,
    constraint TEST_PROGRESS_PK primary key (GROUP_KEY, PARTITION_ID)
);

CREATE TABLE INT_LOCK  (
   LOCK_KEY CHAR(36) NOT NULL,
   REGION VARCHAR(100) NOT NULL,
   CLIENT_ID CHAR(36),
   CREATED_DATE TIMESTAMP NOT NULL,
   EXPIRED_AFTER TIMESTAMP NOT NULL,
   constraint INT_LOCK_PK primary key (LOCK_KEY, REGION)
);
