authors:
  kersten:
    name: Kersten Kriegbaum
    description: Consultant @ Digital Frontiers
    avatar: blog/authors/kersten.jpg
  sebastian:
    name: Sebastian Damrath
    description: Consultant @ Digital Frontiers
    avatar: blog/authors/df-logo.png
