authors:
  kersten:
    name: Kersten Kriegbaum
    description: Consultant @ Digital Frontiers
    avatar: blog/authors/kersten.jpg
  sebastian:
    name: Sebastian D.
    description: Consultant @ Digital Frontiers
    avatar: blog/authors/sebastian.jpg
