name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run All Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Spotless Check
        run: nix develop --impure --command ./gradlew --no-daemon spotlessCheck

      - name: Run Tests
        run: nix develop --impure --command ./gradlew --no-daemon clean test
