name: Run Tests

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: Run All Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run Spotless Check
        run: ./gradlew --no-daemon spotlessCheck

      - name: Run Tests
        run: ./gradlew --no-daemon clean test
