name: Check Code Formatting (Spotless)

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  spotless:
    name: Run Spotless Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck